resume/company/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='company'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<c_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<a_id>[0-9]+)/app_detail/$', views.app_detail, name='app_detail'),
    url(r'add_company/$', views.AddCompany, name="add_company"),
    url(r'add_company_sub/$', views.AddCompanySub, name="add_company_sub"),

    url(r'(?P<p_id>[0-9]+)/add_application/$', views.AddApplication, name="add_application"),
    url(r'add_application_sub/$', views.AddApplicationSub, name="add_application_sub"),
    #url(r'^(?P<a_id>[0-9]+)/external_link/$', views.external_view, name='external_view'),
    #url(r'$', views.Home.as_view(), name='Home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/resume/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^company/', include('company.urls'))
    #path(r'^home/$', views.home, name="home"),
]

resume/company/models.py
from django.db import models

# Create your models here.

class Company(models.Model):
    c_name = models.CharField(max_length=30)
    c_link = models.CharField(max_length=200)

    def __str__(self):
        return self.c_name

class Application(models.Model):
    c_name = models.ForeignKey(Company, on_delete=models.CASCADE)
    profile_name = models.CharField(max_length=50)
    link = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)#Description
    feedback = models.CharField(max_length=100)
    date = models.CharField(max_length=20)
    resume = models.FileField()

    def __str__(self):
        return str(self.c_name) + ' :: '+ self.profile_name




resume/company/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django .template import loader
from company.models import *
from django.views import generic
# Create your views here.

def home(request):

    context={
        'company': Company.objects.all(),
        'app': Application.objects.all()
    }
    template = loader.get_template('Company\home.html')
    return HttpResponse(template.render(context,request))
    #return render(request, template, context)

def detail(request, c_id):
    obj = get_object_or_404(Company, pk = c_id)
    app = Company.objects.get(pk=c_id)
    template = loader.get_template('Company\\app_detail.html')
    context = {
        'app_list': app.application_set.all(),
        'p_id': c_id
    }
    #return render(request, template, context)
    return HttpResponse(template.render(context, request))

def app_detail(request,a_id):
    obj = Application.objects.get(pk= a_id)
    template = loader.get_template('Company\details.html')
    context={
        'obj': obj
    }
    return HttpResponse(template.render(context, request))

#to add company
def AddCompany(request):
    return render(request, "Company/add_company.html")

#store data to database
def AddCompanySub(request):
    print("Company data is submitted successfully")
    c_name = request.POST["c_name"]
    c_link = request.POST["c_link"]
    company_info = Company(c_name = c_name, c_link = c_link)
    company_info.save()

    return render(request, "Company/add_company.html")

#add application
def AddApplication(request, p_id):
    context = {
        'name': Company.objects.get(pk = p_id),
        'company':Company.objects.all()
    }
    return render(request, "Company/add_application.html", context)

#store data in db
def AddApplicationSub(request):
    print("Application submitted successfully")
    w = request.POST["c_name"]
    x = Company.objects.get(c_name = w)
    print(w)
    profile_name = request.POST["profile_name"]
    date = request.POST["date"]
    link = request.POST["link"]
    desc = request.POST["desc"]
    feedback = request.POST["feedback"]
    resume = request.POST["resume"]
    app_info = Application(c_name = x, profile_name = profile_name, date = date, link = link, desc = desc, feedback = feedback, resume = resume)
    app_info.save()
    context = {
        'company': Company.objects.all()
    }
    return render(request, "Company/add_application.html", context)







resume/company/templates/Company/add_application.html
{% extends 'company/header.html' %}
<title>{% block title %}Detail {% endblock %}</title>
<style>
    .row{
    margin:.5%;
    }
</style>
{% block content %}
<div class="container" >
    <div class="row" style="text-algin : center"></div>
    <form class="add_company" method="post" action="add_application_sub/">
        {% csrf_token %}

        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Choose Company Name
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for a in company %}
                <input type="radio" name="c_name" value="{{ a.c_name }}"> {{ a.c_name }}<br>
              {% endfor %}
          </div>
        </div>

        <div class="row form-group" style="font-size: 40px;text-align: center;">{{ name }}</div>

        <div class="row form-group" style="margin:.5%">Profile Name :
            <input name="profile_name" type="text" class="form-control" placeholder="Profile Name">
        </div>
         <div class="row form-group" style="margin:.5%">Date :
            <input name="date" type="text" class="form-control" placeholder="Date">
        </div>
         <div class="row form-group" style="margin:.5%">Link :
            <input name="link" type="text" class="form-control" placeholder="Link">
        </div>
        <div class="row form-group" style="margin:.5%">Description :
            <input name="desc" type="text" class="form-control" rows="5" placeholder="Description">
        </div>
        <div class="row form-group" style="margin:.5%">Feedback :
            <input name="feedback" type="text" class="form-control" placeholder="Feedback">
        </div>
        <div class="row form-group" style="margin:.5%">Resume :
            <input name="resume" type="file" class="form-control-file" placeholder="Resume">
        </div>
        <div class="row" style="text-align: center; margin:.5%" >
            <div class="submit-block table">
                <div class="col-lg-3 table-cell">
                    <button class="btn btn-small btn-primary">
                        <span class="text">Add Application</span>
                    </button>
                </div>
            </div>

        </div>
    </form>

</div>
{% endblock %}

resume/company/templates/Company/add_company.html
{% extends 'company/header.html' %}
<title>{% block title %}Detail {% endblock %}</title>
<style>
    .row{
    margin:.5%;
    }
</style>
{% block content %}
<div class="container" >
    <form class="add_company" method="post" action="add_company_sub/">
        {% csrf_token %}
        <div class="row " style="margin:.5%">Company Name :
            <input name="c_name" class="form-control" placeholder="Company Name">
        </div>
         <div class="row " style="margin:.5%">Company Link :
            <input name="c_link" class="form-control" placeholder="Link">
        </div>
        <div class="row" style="text-align: center; margin:.5%" >
            <div class="submit-block table">
                <div class="col-lg-3 table-cell">
                    <button class="btn btn-small btn-primary">
                        <span class="text">Add Company</span>
                    </button>
                </div>
            </div>

        </div>
    </form>

</div>
{% endblock %}

resume/company/templates/Company/app_detail.html
{% extends 'company/header.html' %}
<title>{% block title %}Detail {% endblock %}</title>
<style>
    .comp{

        }
</style>
{% block content %}
<div class="container" >
    <a href="{% url 'company:add_application' p_id %}">Add Application</a>

    {% for c in app_list %}
        <div class="row comp" style="height: 50px;font-size: 30px;border: solid 1px;border-radius: 15px;padding: .5%;padding-left: 5%;background: wheat;margin:1%;">
            <a href="{% url 'company:app_detail' c.id %}">
            {{ c.profile_name }}
            </a>
        </div>
    {% endfor %}
    <!--<div class="row">

    </div>-->
</div>
{% endblock %}

resume/company/templates/Company/details.html
{% extends 'company/header.html' %}
<title xmlns:http="http://www.w3.org/1999/xhtml" xmlns:http="http://www.w3.org/1999/xhtml"
       xmlns:http="http://www.w3.org/1999/xhtml" xmlns:http="http://www.w3.org/1999/xhtml"
       xmlns:http="http://www.w3.org/1999/xhtml" xmlns:http="http://www.w3.org/1999/xhtml">{% block title %}Details {% endblock %}</title>
<style>
    .comp{

        }
</style>
{% block content %}
<div class="container" >
  <div class="row comp" style="text-align: center; font-size: 30px; color: Green; margin: 1%;">{{ obj.c_name }}</div>
  <div class="row">
    <div class="row col-md-6">Profile Name : <span style="font-size: 25px;">{{ obj.profile_name }}</span></div>
    <div class="row col-md-6">Date : <span style="font-size: 25px;">{{ obj.date }}</span> </div>
  </div>
  <div class="row">
    <div class="row col-md-6">Link : <span style="font-size: 25px;"><a href="{{ obj.link }}" target="_blank">{{ obj.c_name }} Career</a></span></div>
    <div class="row col-md-6">Resume : <span style="font-size: 25px;"><a href="{{ obj.resume.url }}" target="_blank">{{ obj.resume }}</a></span></div>
  </div>
  <div class="row">Description:<br>
    <span style="font-size: 25px;">
      <p>
        {{ obj.desc }}
      </p>
    </span>
  </div>
  <div class="row">Feedback : <span style="font-size: 25px;">{{ obj.feedback }}</span></div>
  <button type="cancel" class="btn btn-primary-default">Back</button>
</div>
{% endblock %}

resume/company/templates/Company/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Home {% endblock%}</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>

        @media only screen and (max-width: 766) {
          #tipnavbar ul{
            text-align:center;
          }
        }
    </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Resume</a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tipnavbar" >
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
    </div>
      <div class="collapse navbar-collapse" id="tipnavbar">
          <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'company:home' %}">
                  <i class="fa fa-home" style="font-size:24px"> Home</i></a></li>
              <li><a href="#">Page 1</a></li>
              <li><a href="#">Page 2</a></li>
              <li><a href="add_company/">Add Company</a></li>
          </ul>
          <ul class="nav navbar-nav" style="float:right; font-size:20px">
              <li><a href="#"><i class="fa fa-sign-in" >   Login</i></a></li>
              <li><a href="#"><i class="fa fa-user-plus">  Register</i></a></li>
          </ul>
      </div>
  </div>
</nav>

<div class="container" >

  {% block content %}

    {% endblock %}
</div>

</body>
</html>

resume/company/templates/Company/home.html
{% extends 'company/header.html' %}
<style>
    .comp{

        }
</style>
{% block content %}
<div class="container" >
    {% for c in company %}
        <div class="row comp" style="height: 50px;
        font-size: 30px;
        border: solid 1px;
        border-radius: 15px;
        padding: .5%;
        padding-left: 5%;
        background: wheat;
        margin:1%;">
        <a href="{% url 'company:detail' c.id %}">
            {{ c.c_name }}
        </a>
        </div>
    {% endfor %}
</div>
{% endblock %}